#!/usr/bin/env perl
# vim: ft=perl

use strict;
use warnings;
use Bot;

BEGIN {
    *exp_continue = *Expect::exp_continue;
    *exp_continue_timeout = *Expect::exp_continue_timeout;
}


sub Bot::hook {
    my ($expect, $hostname) = @_;
    my $rt;

    my $user = 'szbrhv';
    my $password = 'foobar1003';

    $rt = $expect->execute({ command => 'uname -s' });
    if ($rt->worked) {
        if ($rt->first_line eq 'AIX') {
#            use ResetPassword::AIX qw[ reset_password ];
#            try {
#                reset_password($expect, $user, $password);
#            } catch {
#            };
        }
        elsif ($rt->first_line eq 'SunOS') {
            use ResetPassword::Solaris qw[ reset_password ];
            my $username = 'foobar'; # XXX don't forgot to implement the code for usernames.
            try {
                reset_password($expect, $username);
            } catch {
            };
        }
    }
    return $rt;
}

